# Generated by Django 3.2.7 on 2021-09-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allTeam',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=30)),
                ('winningYears', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=80)),
            ],
        ),
    ]
